%% CONFIGS

addpath(fullfile('C:\Users', getenv('username'), ...
                 'MATLAB Drive', 'UAS Design', 'StabCon',...
                 'Calcs', 'Conventional_Tail', 'Configurations'));

addpath(fullfile('C:\Users', getenv('username'), ...
                 'MATLAB Drive', 'UAS Design', 'StabCon',...
                 'Calcs', 'Conventional_Tail', 'Aero'));

addpath(fullfile('C:\Users', getenv('username'), ...
                 'MATLAB Drive', 'UAS Design', 'StabCon',...
                 'Calcs', 'Conventional_Tail', 'Plotting'));

addpath(fullfile('C:\Users', getenv('username'), ...
                 'MATLAB Drive', 'UAS Design', 'StabCon',...
                 'Calcs', 'Conventional_Tail', 'Plotting',...
                 'PlotCalcs'));

addpath(fullfile('C:\Users', getenv('username'), ...
                 'MATLAB Drive', 'UAS Design', 'StabCon',...
                 'Calcs', 'Conventional_Tail', 'Plotting',...
                 'Plots'));

addpath(fullfile('C:\Users', getenv('username'), ...
                 'MATLAB Drive', 'UAS Design', 'StabCon',...
                 'Calcs', 'Conventional_Tail', 'Plotting',...
                 'Shapes'));

addpath(fullfile('C:\Users', getenv('username'), ...
                 'MATLAB Drive', 'UAS Design', 'StabCon',...
                 'Calcs', 'Conventional_Tail', 'StabCon'));

configs = struct();
configs = Inputs(configs);

names = fieldnames(configs);

for i = 1:length(names)
    x = names{i};
    configs.(x).data = Main(configs.(x).data);
    filename = sprintf('AircraftDynConstants_%d.txt', i);
    writeAircraftDataFile(filename, configs.(x).data);
end

plotAllData(configs, names{1})

save("Data.mat")