function [lines] = TextOut(data, configName)
lines = {};

% User and time info
userID = getenv('USERNAME');  % Use 'USER' on Unix-based systems
if isempty(userID)
    userID = getenv('USER');
end
timestamp = datetime('now', 'Format', 'dd-MMM-yyyy HH:mm:ss');

lines{end+1} = sprintf('Customer %s', userID);
lines{end+1} = sprintf('Run at %s', timestamp);
lines{end+1} = '';
lines{end+1} = '-----------------------------------------------------------------------------------------------------';
lines{end+1} = sprintf('| UNIVERSITY OF BATH\t\t\t\t\t\t\t\t\t\t|');
lines{end+1} = sprintf('|\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t|');
lines{end+1} = sprintf('| PROGRAM TRIMDAP\t\t\t\t\t\t\t\t\t\t\t|');
lines{end+1} = sprintf('|\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t|');
lines{end+1} = sprintf('| TRIMDAP Version:  1.0  April 2025\t\t\t\t\t\t\t\t|');
lines{end+1} = sprintf('|\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t|');
lines{end+1} = sprintf('| (See README for full input/output specification and interpretation)\t\t|');
lines{end+1} = '-----------------------------------------------------------------------------------------------------';
lines{end+1} = '';
lines{end+1} = 'Input Configuration Data';
lines{end+1} = '-----------------------------------------------------------------------|';
lines{end+1} = '';
lines{end+1} = sprintf('Configuration Name: %s', configName);
lines{end+1} = '';
lines{end+1} = 'Aircraft Components:';
lines{end+1} = '';

% Loop through components
type1 = fieldnames(data.cmpnt);
for i1 = 1:length(type1)
    sec1 = type1{i1};
    type2 = fieldnames(data.cmpnt.(sec1));
    for i2 = 1:length(type2)
        sec2 = type2{i2};
        comp = data.cmpnt.(sec1).(sec2);
        lines{end+1} = '----------------------------'; %#ok<*AGROW>
        lines{end+1} = sprintf('Component Name:\ndata.cmpnt.%s.%s', sec1, sec2);
        lines{end+1} = '';
        lines{end+1} = sprintf('Mass\t\t\t= %.2f kg', comp.m);
        lines{end+1} = '';
        lines{end+1} = sprintf('X\t\t\t\t= %.2f m', comp.x);
        lines{end+1} = sprintf('Y\t\t\t\t= %.2f m', comp.y);
        lines{end+1} = sprintf('Z\t\t\t\t= %.2f m', comp.z);
        lines{end+1} = '';
        lines{end+1} = sprintf('X length\t\t\t= %.2f m', comp.xl);
        lines{end+1} = sprintf('Y length\t\t\t= %.2f m', comp.yl);
        lines{end+1} = sprintf('Z length\t\t\t= %.2f m', comp.zl);
        lines{end+1} = '----------------------------';
    end
end

lines{end+1} = '';
lines{end+1} = 'Conditions';
lines{end+1} = '';
lines{end+1} = sprintf('Velocity\t= %.1f m/s', data.stage.loiter.v);
lines{end+1} = sprintf('Altitude\t= %.0f ft', data.stage.loiter.altft);
lines{end+1} = '';
lines{end+1} = 'Output Data';
lines{end+1} = '-----------------------------------------------------------------------|';
lines{end+1} = 'All for conditions to trim';
lines{end+1} = '';
lines{end+1} = sprintf('Aircraft Weight\t\t\t= %.2f N', data.totalw);
lines{end+1} = sprintf('Aircraft Mass\t\t\t\t= %.3f kg', data.totalw / 9.81);
lines{end+1} = '';
lines{end+1} = 'Wing:';
lines{end+1} = '---------------------------------------------------------';
lines{end+1} = sprintf('Wing span\t\t\t\t= %.3f m', data.cmpnt.cntrlSurf.wing.yl);
lines{end+1} = sprintf('Wing area\t\t\t\t= %.3f m²', data.cmpnt.cntrlSurf.wing.(data.use.wing).S);
lines{end+1} = sprintf('Wing shape\t\t\t\t= %s', data.use.wing);
lines{end+1} = sprintf('Wing CL_wb\t\t\t\t= %.3f', data.cmpnt.cntrlSurf.wing.(data.use.wing).CL);
lines{end+1} = sprintf('Wing AoA set\t\t\t\t= %.3f deg', data.cmpnt.cntrlSurf.wing.(data.use.wing).alpha);
lines{end+1} = sprintf('Wing Alpha Zero Lift\t\t= %.3f deg', data.cmpnt.cntrlSurf.wing.alphaL0);
lines{end+1} = sprintf('Wing Load\t\t\t\t= %.2f N', data.cmpnt.cntrlSurf.wing.Lift);
lines{end+1} = sprintf('Wing CLMAX\t\t\t\t= %.2f', data.stabcon.CLMAX);
lines{end+1} = '---------------------------------------------------------';
lines{end+1} = '';
lines{end+1} = 'Tail:';
lines{end+1} = '---------------------------------------------------------';
lines{end+1} = sprintf('Tail span\t\t\t\t\t= %.3f m', data.cmpnt.cntrlSurf.tail.yl);
lines{end+1} = sprintf('Tail area\t\t\t\t\t= %.3f m²', data.cmpnt.cntrlSurf.tail.(data.use.tail).S);
lines{end+1} = sprintf('Tail shape\t\t\t\t= %s', data.use.tail);
lines{end+1} = sprintf('Tail CL_t\t\t\t\t\t= %.3f', data.cmpnt.cntrlSurf.tail.(data.use.tail).CL);
lines{end+1} = sprintf('Tail AoA set\t\t\t\t= %.3f deg', data.cmpnt.cntrlSurf.tail.(data.use.tail).alpha);
lines{end+1} = sprintf('Tail Alpha Zero Lift\t\t\t= %.3f deg', data.cmpnt.cntrlSurf.tail.alphaL0);
lines{end+1} = sprintf('Tail Load\t\t\t\t\t= %.2f N', data.cmpnt.cntrlSurf.tail.Lift);
lines{end+1} = sprintf('Max Tail CL_t\t\t\t\t= %.2f', data.stabcon.maxCLt);
lines{end+1} = sprintf('Max Tail Load\t\t\t\t= %.2f N', data.stabcon.maxLt);
lines{end+1} = '---------------------------------------------------------';
lines{end+1} = '';
lines{end+1} = 'Vertical Tail:';
lines{end+1} = '---------------------------------------------------------';
lines{end+1} = sprintf('Vert Tail span\t\t\t\t= %.3f m', data.cmpnt.cntrlSurf.Vstab.yl);
lines{end+1} = sprintf('Vert Tail area\t\t\t\t= %.3f m²', data.cmpnt.cntrlSurf.Vstab.(data.use.Vstab).S);
lines{end+1} = sprintf('Vert Tail shape\t\t\t= %s', data.use.Vstab);
lines{end+1} = '---------------------------------------------------------';
lines{end+1} = '';
lines{end+1} = 'Longitudinal Stability and Control Constants:';
lines{end+1} = '---------------------------------------------------------';
lines{end+1} = sprintf('h0 (AC)\t\t\t\t\t= %.3f m', data.stabcon.h0);
lines{end+1} = sprintf('h (c.g.)\t\t\t\t\t= %.3f m', data.stabcon.h);
lines{end+1} = sprintf('CL\t\t\t\t\t\t= %.3f', data.stabcon.CL);
lines{end+1} = sprintf('Vbar\t\t\t\t\t= %.3f', data.stabcon.Vbar);
lines{end+1} = sprintf('CM0\t\t\t\t\t= %.3f', data.stabcon.CM0);
lines{end+1} = sprintf('etaT\t\t\t\t\t\t= %.2f deg', deg(data.stabcon.etaT));
lines{end+1} = sprintf('d(eta)/d(alpha)\t\t\t= %.3f', data.stabcon.DeDalpha);
lines{end+1} = sprintf('e0\t\t\t\t\t\t= %.3f', data.stabcon.e0);
lines{end+1} = sprintf('mu1\t\t\t\t\t\t= %.3f', data.stabcon.mu1);
lines{end+1} = sprintf('a  (wing slope)\t\t\t\t= %.3f', data.stabcon.a);
lines{end+1} = sprintf('a1 (tail slope)\t\t\t\t= %.3f', data.stabcon.a1);
lines{end+1} = sprintf('a2 (elevator slope)\t\t\t= %.3f', data.stabcon.a2);
lines{end+1} = sprintf('S (wing area)\t\t\t\t= %.3f m²', data.stabcon.S);
lines{end+1} = sprintf('St (tail area)\t\t\t\t= %.3f m²', data.stabcon.St);
lines{end+1} = sprintf('cBar (mean chord)\t\t\t= %.3f m', data.stabcon.cbar);
lines{end+1} = sprintf('l (AC)\t\t\t\t\t= %.3f m', data.stabcon.l);
lines{end+1} = sprintf('lt (c.g.)\t\t\t\t\t= %.3f m', data.stabcon.lt);
lines{end+1} = sprintf('CDi\t\t\t\t\t\t= %.3f m', data.stabcon.CDi);
lines{end+1} = sprintf('CDb\t\t\t\t\t\t= %.3f m', data.stabcon.CDb);
lines{end+1} = '';
lines{end+1} = 'Lateral Stability and Control Constants:';
lines{end+1} = '---------------------------------------------------------';
lines{end+1} = sprintf('Vert tail coefficient (VertVbar)\t= %.3f', data.stabcon.VertVbar);
lines{end+1} = sprintf('av  (Vert tail slope)\t\t\t= %.3f', data.stabcon.av);
lines{end+1} = sprintf('lv (c.g.)\t\t\t\t\t= %.3f m', data.stabcon.lv);
lines{end+1} = sprintf('Sv (Vert tail area)\t\t\t= %.3f m²', data.stabcon.Sv);
lines{end+1} = '';
lines{end+1} = 'Main Results:';
lines{end+1} = '---------------------------------------------------------';
lines{end+1} = sprintf('KN\t\t\t\t\t\t= %.3f', data.stabcon.Kn);
lines{end+1} = sprintf('hn\t\t\t\t\t\t= %.3f', data.stabcon.hn);
lines{end+1} = sprintf('etaBar\t\t\t\t\t= %.2f deg', deg(data.stabcon.etaBar));
lines{end+1} = sprintf('Hm (moment arm)\t\t\t= %.3f', data.stabcon.Hm);
lines{end+1} = sprintf('hm (moment arm)\t\t\t= %.3f', data.stabcon.hm);
lines{end+1} = sprintf('c.g. range no buf\t\t\t= %.3f - %.3f', data.stabcon.hfwd * data.stabcon.cbar, data.stabcon.haft * data.stabcon.cbar);
lines{end+1} = sprintf('c.g. range no buf %% of MAC\t= %.3f', (data.stabcon.haft * data.stabcon.cbar - data.stabcon.hfwd * data.stabcon.cbar) / data.stabcon.cbar);
lines{end+1} = sprintf('c.g. range buf\t\t\t\t= %.3f - %.3f', data.stabcon.hfwd * data.stabcon.cbar * 1.05, data.stabcon.haft * data.stabcon.cbar * 0.95);
lines{end+1} = sprintf('c.g. range buf %% of MAC\t\t= %.3f', ((data.stabcon.haft * data.stabcon.cbar * 0.95) - (data.stabcon.hfwd * data.stabcon.cbar * 1.05)) / data.stabcon.cbar);
lines{end+1} = '';
lines{end+1} = 'Control Surfaces:';
lines{end+1} = '---------------------------------------------------------';
lines{end+1} = sprintf('aa  (aileron slope)\t\t\t= %.3f', data.stabcon.aa);
lines{end+1} = sprintf('Aileron singular span\t\t= %.3f', data.cmpnt.cntrlSurf.aileron1.yl);
lines{end+1} = sprintf('Aileron chord\t\t\t\t= %.3f', data.cmpnt.cntrlSurf.aileron1.xl);
lines{end+1} = sprintf('la\t\t\t\t\t\t= %.3f', data.cmpnt.cntrlSurf.aileron1.y);
lines{end+1} = sprintf('Aileron tot span / Wing span\t= %.3f', (data.cmpnt.cntrlSurf.aileron1.yl * 2) / data.cmpnt.cntrlSurf.wing.yl);
lines{end+1} = sprintf('Aileron chord / Wing chord\t= %.3f', data.cmpnt.cntrlSurf.aileron1.xl / data.cmpnt.cntrlSurf.wing.xl);
lines{end+1} = sprintf('Aileron Force Required\t\t= %.3f N', data.aeroData.cmpnt.cntrlSurf.aileron1.LiftMax);
lines{end+1} = sprintf('Aileron Moment Arm\t\t= %.3f m', data.cmpnt.cntrlSurf.aileron1.xl * 1/4);
lines{end+1} = '';
lines{end+1} = sprintf('a2 (elevator slope)\t\t\t= %.3f', data.stabcon.a2);
lines{end+1} = sprintf('Elevator singular span\t\t= %.3f', data.cmpnt.cntrlSurf.elevator1.yl);
lines{end+1} = sprintf('Elevator chord\t\t\t\t= %.3f', data.cmpnt.cntrlSurf.elevator1.xl);
lines{end+1} = sprintf('Elevator tot span / Tail span\t= %.3f', (data.cmpnt.cntrlSurf.elevator1.yl * 2) / data.cmpnt.cntrlSurf.tail.yl);
lines{end+1} = sprintf('Elevator chord / Tail chord\t= %.3f', data.cmpnt.cntrlSurf.elevator1.xl / data.cmpnt.cntrlSurf.tail.xl);
lines{end+1} = sprintf('Elevator Force Required\t\t= %.3f N', data.aeroData.cmpnt.cntrlSurf.elevator1.LiftMax);
lines{end+1} = sprintf('Elevator Moment Arm\t\t= %.3f m', data.cmpnt.cntrlSurf.elevator1.xl * 1/4);
lines{end+1} = '';
lines{end+1} = sprintf('ar (rudder slope)\t\t\t= %.3f', data.stabcon.ar);
lines{end+1} = sprintf('Rudder height\t\t\t\t= %.3f', data.cmpnt.cntrlSurf.rudder.zl);
lines{end+1} = sprintf('Rudder chord\t\t\t\t= %.3f', data.cmpnt.cntrlSurf.rudder.xl);
lines{end+1} = sprintf('Rudder height / Vert T height\t= %.3f', data.cmpnt.cntrlSurf.rudder.zl / data.cmpnt.cntrlSurf.Vstab.zl);
lines{end+1} = sprintf('Rudder chord / Vert T chord\t= %.3f', data.cmpnt.cntrlSurf.rudder.xl / data.cmpnt.cntrlSurf.Vstab.xl);
lines{end+1} = sprintf('Rudder Force Required\t\t= %.3f N', data.aeroData.cmpnt.cntrlSurf.rudder.LiftMax);
lines{end+1} = sprintf('Rudder Moment Arm\t\t= %.3f m', data.cmpnt.cntrlSurf.rudder.xl * 1/4);
lines{end+1} = '';
lines{end+1} = 'V-Tail Equivilent:';
lines{end+1} = '---------------------------------------------------------';
lines{end+1} = sprintf('Total S\t\t\t\t\t= %.3f m²', data.stabcon.Vtail.S);
lines{end+1} = sprintf('One side S\t\t\t\t= %.3f m²', data.stabcon.Vtail.S1);
lines{end+1} = sprintf('Angle\t\t\t\t\t= %.3f deg', deg(data.stabcon.Vtail.angle));
lines{end+1} = sprintf('Chord\t\t\t\t\t= %.3f m', data.stabcon.Vtail.chord);
lines{end+1} = sprintf('Total span\t\t\t\t= %.3f m', data.stabcon.Vtail.b);
lines{end+1} = sprintf('One side span\t\t\t\t= %.3f m', data.stabcon.Vtail.b1);
lines{end+1} = sprintf('Flat span\t\t\t\t\t= %.3f m', data.stabcon.Vtail.flatspan);
lines{end+1} = '';
lines{end+1} = 'Landing Results:';
lines{end+1} = '---------------------------------------------------------';
lines{end+1} = sprintf('Velocity\t\t\t\t\t\t= %.3f m/s', data.stabcon.Vl);
lines{end+1} = sprintf('CL (no flaps)\t\t\t\t\t= %.3f', data.stabcon.CLWL);
lines{end+1} = sprintf('CL flaps\t\t\t\t\t\t= %.3f', data.stabcon.CLFLAPS);
lines{end+1} = sprintf('CL Total\t\t\t\t\t\t= %.3f', data.stabcon.CLLAND);
lines{end+1} = sprintf('Required elevator deflection\t\t= %.3f deg', deg(data.stabcon.etaBarLand));
lines{end+1} = sprintf('CLt\t\t\t\t\t\t\t= %.3f', data.stabcon.CLtLAND);
lines{end+1} = '';
lines{end+1} = 'Take-Off Rotation Results:';
lines{end+1} = '---------------------------------------------------------';
lines{end+1} = sprintf('Stall Velocity\t\t\t\t\t= %.3f m/s', data.stabcon.Vs);
lines{end+1} = sprintf('Rotation Velocity\t\t\t\t= %.3f m/s', data.stabcon.Vr);
lines{end+1} = sprintf('CL (no flaps)\t\t\t\t\t= %.3f', data.stabcon.CLW);
lines{end+1} = sprintf('CL flaps\t\t\t\t\t\t= %.3f', data.stabcon.CLFLAPS);
lines{end+1} = sprintf('CL Total\t\t\t\t\t\t= %.3f', data.stabcon.CLTO);
lines{end+1} = sprintf('CD\t\t\t\t\t\t\t= %.3f', data.stabcon.CDTO);
lines{end+1} = sprintf('Thrust\t\t\t\t\t\t= %.3f N', data.prop.thrust);
lines{end+1} = sprintf('CLt\t\t\t\t\t\t\t= %.3f', data.stabcon.CLtTO);
lines{end+1} = sprintf('Lt\t\t\t\t\t\t\t= %.3f N', data.stabcon.LtTO);
lines{end+1} = sprintf('Acceleration\t\t\t\t\t= %.3f m/s²', data.stabcon.TOa);
lines{end+1} = sprintf('Elevator deflection effectiveness\t= %.3f', data.stabcon.Te);
lines{end+1} = sprintf('Wheel reaction\t\t\t\t= %.3f N', data.stabcon.RTO);
lines{end+1} = sprintf('Pitching moment coefficent\t\t= %.3f', data.stabcon.CMref);
lines{end+1} = sprintf('Pitching moment\t\t\t\t= %.3f', data.stabcon.Ma);
lines{end+1} = '';
lines{end+1} = 'Program completed';
lines{end+1} = '-----------------------------------------------------------------------|';
end