function [x, y] = TaperedPlot(data, s)
% Draw tapered straight
rootChord = data.cmpnt.cntrlSurf.(s).(data.use.(s)).c;  % Root chord length
tipChord = rootChord * data.cmpnt.cntrlSurf.(s).(data.use.(s)).taperR; % Tip chord length
totalwidth = data.cmpnt.cntrlSurf.(s).yl;
semiSpan = totalwidth / 2;

% Define wing coordinates with six vertices
x = [data.cmpnt.cntrlSurf.(s).x + rootChord / 2, ...
         data.cmpnt.cntrlSurf.(s).x + tipChord / 2, ...
         data.cmpnt.cntrlSurf.(s).x - tipChord / 2, ...
         data.cmpnt.cntrlSurf.(s).x - rootChord / 2, ...
         data.cmpnt.cntrlSurf.(s).x - tipChord / 2, ...
         data.cmpnt.cntrlSurf.(s).x + tipChord / 2];

y = [data.cmpnt.cntrlSurf.(s).y,...
    data.cmpnt.cntrlSurf.(s).y + semiSpan,...
    data.cmpnt.cntrlSurf.(s).y + semiSpan,...
    data.cmpnt.cntrlSurf.(s).y,...
    data.cmpnt.cntrlSurf.(s).y - semiSpan,...
    data.cmpnt.cntrlSurf.(s).y - semiSpan];
end