function [x, y] = VTriangularPlot(data, s)
% Draw tapered straight
rootChord = data.cmpnt.cntrlSurf.(s).(data.use.(s)).c;  % Root chord length
tipChord = rootChord * data.cmpnt.cntrlSurf.(s).(data.use.(s)).taperR; % Tip chord length
totalwidth = data.cmpnt.cntrlSurf.(s).xl;

% Define wing coordinates with six vertices
x = [data.cmpnt.cntrlSurf.(s).x - totalwidth / 2, ...
         data.cmpnt.cntrlSurf.(s).x + totalwidth / 2 - tipChord, ...
         data.cmpnt.cntrlSurf.(s).x + totalwidth / 2, ...
         data.cmpnt.cntrlSurf.(s).x + totalwidth / 2];

y = [data.cmpnt.cntrlSurf.(s).z,...
    data.cmpnt.cntrlSurf.(s).z + data.cmpnt.cntrlSurf.(s).zl,...
    data.cmpnt.cntrlSurf.(s).z + data.cmpnt.cntrlSurf.(s).zl,...
    data.cmpnt.cntrlSurf.(s).z];
end